name: easyreflectometry
summary: Making reflectometry data analysis and modelling easy.
description: |
   EasyReflectometry is a scientific software for modelling and analysis of reflectometry data.
   Currently, EasyReflectometry covers single contrast measurements of layered structures.
adopt-info: build-application
grade: stable
confinement: strict
base: core20
icon: resources/images/er_logo.svg
architectures:
    - build-on: [amd64]

environment:
    PYTHONPATH: $SNAP:$PYTHONPATH
    DISABLE_WAYLAND: 1

apps:
    easyreflectometry:
        command: easy-reflectometry-wrapper
        extensions: [gnome-3-38]
        plugs: [network, x11, pulseaudio, opengl, home, ssh-keys, shmem]

parts:
    copy-stuff:
        plugin: dump
        source: .

    build-application:
        plugin: python
        source: .

        override-pull: |
            snapcraftctl pull
            snapcraftctl set-version "$(cat pyproject.toml | grep version | head -n 1 | awk -F'"' '$0=$2' | sed 's/ //g')"

        stage-packages:
            - python3.10
            - libfreetype6
            - libgomp1
            - libpng16-16
            - libxcb-xinerama0
            - libxkbcommon0
            - libxcb-render0
            - libxcb-randr0
            - libnss3
            - unixodbc-dev
            - libpq-dev
            - libxcb-icccm4
            - libxkbcommon-x11-0
            - libxcb-xkb1
            - libxcb-render-util0
            - libxcb-shape0
            - libspeechd2
            - libxcb-image0
            - libxcb-keysyms1
            - libxcb-util1
        build-packages:
            - python3.10
            - git-all
            - pipenv
        build-environment:
            - SNAPCRAFT_PYTHON_INTERPRETER: python3.10
            - PATH: $SNAPCRAFT_PART_INSTALL/bin:$PATH
            - PYTHONPATH: ''

plugs:
  shmem:
    interface: shared-memory
    private: true
