# This pipeline
# - build developer documentation
# - push documentation to gh-pages branch of the same repository
#
# Deployment is handled by pages-build-deployment bot
#
# This pipeline DOES NOT build the end-user page

name: Build Documentation and Push to gh-pages Branch 

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install EasyReflectometry and dependencies
      run: |
        sudo apt install pandoc
        pip install '.[docs]'
    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        install_requirements: true
        documentation_path: docs
    - name: Push changes
      uses: ad-m/github-push-action@master
      continue-on-error: true
      with:
        branch: gh-pages